import { Type } from 'class-transformer'
import {
  ArrayMaxSize,
  ArrayNotEmpty,
  IsArray,
  IsInt,
  IsString,
  IsUUID,
  Length,
  Min,
  ValidateNested
} from 'class-validator'
import { ApiProperty } from '@nestjs/swagger'

export class CreateOrderItemDto {
  @ApiProperty({
    example: '0d6cd087-3f2e-4f30-b0aa-cf9c93b1c0d5',
    description: 'Identifier of the product being purchased'
  })
  @IsUUID()
  productId: string

  @ApiProperty({ example: 2, description: 'Units to purchase', minimum: 1 })
  @IsInt()
  @Min(1)
  quantity: number
}

export class CreateOrderDto {
  @ApiProperty({
    type: [CreateOrderItemDto],
    description:
      'Lines to purchase. Prices are never accepted here: the total is calculated from the catalog'
  })
  @IsArray()
  @ArrayNotEmpty()
  @ArrayMaxSize(100)
  @ValidateNested({ each: true })
  @Type(() => CreateOrderItemDto)
  items: CreateOrderItemDto[]

  @ApiProperty({
    example: '3f7b1c92-5d2e-4c8a-b1f0-6a9e2d4c8b31',
    description:
      'Generated by the client when the checkout starts, not when confirm is pressed. Replaying it returns the existing order'
  })
  @IsString()
  @Length(8, 100)
  idempotencyKey: string
}
