import { Transform, Type } from 'class-transformer'
import {
  ArrayMaxSize,
  ArrayNotEmpty,
  IsArray,
  IsEmail,
  IsInt,
  IsNotEmpty,
  IsObject,
  IsString,
  IsUUID,
  Length,
  Min,
  ValidateNested
} from 'class-validator'
import { ApiProperty } from '@nestjs/swagger'

import { trimText } from '@/common/transformers/sanitize.transformer'
import { NoHtml } from '@/common/validators/no-html.validator'

/**
 * Where the order is delivered. Required: recording an order nobody can deliver
 * is worse than refusing it. Shipping is still not priced — the total comes
 * from the lines alone.
 */
export class ShippingAddressDto {
  @ApiProperty({ example: 'Ada Lovelace', maxLength: 255 })
  @Transform(({ value }) => trimText(value))
  @IsString()
  @IsNotEmpty()
  @Length(1, 255)
  @NoHtml()
  name: string

  @ApiProperty({ example: '+14155552671', maxLength: 30 })
  @Transform(({ value }) => trimText(value))
  @IsString()
  @IsNotEmpty()
  @Length(1, 30)
  @NoHtml()
  phone: string

  // No @NoHtml(): @IsEmail() already rejects anything that is not an address,
  // markup included.
  @ApiProperty({ example: 'ada@example.com', maxLength: 255 })
  @Transform(({ value }) => trimText(value))
  @IsString()
  @IsNotEmpty()
  @Length(1, 255)
  @IsEmail()
  email: string

  @ApiProperty({ example: '1 Test Street', maxLength: 255 })
  @Transform(({ value }) => trimText(value))
  @IsString()
  @IsNotEmpty()
  @Length(1, 255)
  @NoHtml()
  address: string

  @ApiProperty({ example: 'Springfield', maxLength: 100 })
  @Transform(({ value }) => trimText(value))
  @IsString()
  @IsNotEmpty()
  @Length(1, 100)
  @NoHtml()
  city: string

  @ApiProperty({ example: 'IL', maxLength: 100 })
  @Transform(({ value }) => trimText(value))
  @IsString()
  @IsNotEmpty()
  @Length(1, 100)
  @NoHtml()
  state: string

  @ApiProperty({ example: '62701', maxLength: 20 })
  @Transform(({ value }) => trimText(value))
  @IsString()
  @IsNotEmpty()
  @Length(1, 20)
  @NoHtml()
  zipCode: string

  @ApiProperty({ example: 'United States', maxLength: 100 })
  @Transform(({ value }) => trimText(value))
  @IsString()
  @IsNotEmpty()
  @Length(1, 100)
  @NoHtml()
  country: string
}

export class CreateOrderItemDto {
  @ApiProperty({
    example: '0d6cd087-3f2e-4f30-b0aa-cf9c93b1c0d5',
    description: 'Identifier of the product being purchased'
  })
  @IsUUID()
  productId: string

  @ApiProperty({ example: 2, description: 'Units to purchase', minimum: 1 })
  @IsInt()
  @Min(1)
  quantity: number
}

export class CreateOrderDto {
  @ApiProperty({
    type: [CreateOrderItemDto],
    description:
      'Lines to purchase. Prices are never accepted here: the total is calculated from the catalog'
  })
  @IsArray()
  @ArrayNotEmpty()
  @ArrayMaxSize(100)
  @ValidateNested({ each: true })
  @Type(() => CreateOrderItemDto)
  items: CreateOrderItemDto[]

  @ApiProperty({
    example: '3f7b1c92-5d2e-4c8a-b1f0-6a9e2d4c8b31',
    description:
      'A UUID generated by the client when the checkout starts, not when confirm is pressed. Replaying it returns the existing order'
  })
  // A UUID rather than any string of eight characters or more: placing an order
  // needs no session, and replaying a key returns the order it belongs to,
  // shipping address included. A guessable key is therefore a way to read
  // somebody else's delivery details.
  @IsUUID()
  idempotencyKey: string

  @ApiProperty({
    type: ShippingAddressDto,
    description:
      'Where the order is delivered. Stored with the order and never altered afterwards'
  })
  @IsObject()
  @ValidateNested()
  @Type(() => ShippingAddressDto)
  shippingAddress: ShippingAddressDto
}
